name: Deploy to Vercel
on:
  push:
    branches:
      - main  # replace with your default branch if not "main"
  workflow_dispatch:  # This line adds a manual trigger
    branches:
      - main  # replace with your default branch if not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - uses: amondnet/vercel-action@v20 #deploy
      with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./sub-directory
