name: Deploy to Vercel
on:
  push:
    branches:
      - main  # replace with your default branch if not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci
          
    - name: Build
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}  # set this in your repo's secrets
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # set this in your repo's secrets
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # set this in your repo's secrets
        github-token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically creates this secret
